<?php

function classic(){

	$default1 = includes_url( 'images/smilies/' );

	$emo='<img src="'; $emo.=$default1; $emo.='icon_mrgreen.gif" alt=":mrgreen:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='icon_twisted.gif" alt=":twisted:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='icon_arrow.gif" alt=":arrow:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='icon_eek.gif" alt="8|" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='icon_smile.gif" alt=":)" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='icon_confused.gif" alt=":?" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='icon_evil.gif" alt=":evil:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='icon_biggrin.gif" alt=":D" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='icon_idea.gif" alt=":idea:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='icon_redface.gif" alt=":oops:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='icon_razz.gif" alt=":razz:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='icon_rolleyes.gif" alt=":roll:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='icon_cry.gif" alt=":cry2:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='icon_surprised.gif" alt=":eek:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='icon_mad.gif" alt=":mad:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='icon_sad.gif" alt=":sad:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='icon_cool.gif" alt="8-)" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='icon_eek.gif" alt="8-O" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='icon_sad.gif" alt=":-(" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='icon_smile.gif" alt=":-)" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='icon_confused.gif" alt=":-?" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='icon_biggrin.gif" alt=":-D" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='icon_razz.gif" alt=":-P" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='icon_surprised.gif" alt=":-o" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='icon_mad.gif" alt=":-x" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='icon_neutral.gif" alt=":-|" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='icon_wink.gif" alt=";-)" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='icon_exclaim.gif" alt=":!:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='icon_question.gif" alt=":?:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='mario.gif" alt=":mario:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='fantasma.gif" alt=":fantasma:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='pacman.gif" alt=":pacman:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='lala.gif" alt=":lala:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='grin.gif" alt=":grin:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='love.gif" alt=":love:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='winky.gif" alt=":winky:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='blaf.gif" alt=":blaf:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='bobo.gif" alt=":bobo:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='globo.gif" alt=":globo:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='metal.gif" alt=":metal:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='info.gif" alt=":info:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='exc.gif" alt=":exc:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='q.gif" alt=":q:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='wow.gif" alt=":wow:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='lol.gif" alt=":lol:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='idiot.gif" alt=":idiot:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='lpmqtp.gif" alt=":lpmqtp:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='8s.gif" alt=":8s:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='bang.gif" alt=":headbang:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='no.gif" alt=":no:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='ok.gif" alt=":ok:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='shrug.gif" alt=":shrug:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='crying.gif" alt=":crying:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='noo.gif" alt=":noo:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='zombie.gif" alt=":zombie:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='cold.gif" alt=":cold:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='hot.gif" alt=":hot:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='blind.gif" alt=":blind:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default1; $emo.='drool.gif" alt=":drool:" id="emoca" class="wp-smiley">';

return $emo;

}

function People(){

	$default2 = includes_url( 'images/smilies/emojis/' );

	$emo='<img src="'; $emo.=$default2; $emo.='bowtie.png" alt=":bowtie:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='smile.png" alt=":smile:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='laughing.png" alt=":laughing:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='blush.png" alt=":blush:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='smiley.png" alt=":smiley:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='relaxed.png" alt=":relaxed:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='smirk.png" alt=":smirk:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='heart_eyes.png" alt=":heart_eyes:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='kissing_heart.png" alt=":kissing_heart:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='kissing_closed_eyes.png" alt=":kissing_closed_eyes:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='flushed.png" alt=":flushed:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='relieved.png" alt=":relieved:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='satisfied.png" alt=":satisfied:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='wink.png" alt=":wink:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='stuck_out_tongue_winking_eye.png" alt=":wink2:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='stuck_out_tongue_winking_eye.png" alt=":stuck_out_tongue_winking_eye:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='stuck_out_tongue_closed_eyes.png" alt=":stuck_out_tongue_closed_eyes:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='grinning.png" alt=":grinning:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='kissing.png" alt=":kissing:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='kissing_smiling_eyes.png" alt=":kissing_smiling_eyes:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='stuck_out_tongue.png" alt=":stuck_out_tongue:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='sleeping.png" alt=":sleeping:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='worried.png" alt=":worried:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='frowning.png" alt=":frowning:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='anguished.png" alt=":anguished:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='open_mouth.png" alt=":open_mouth:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='grimacing.png" alt=":grimacing:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='confused.png" alt=":confused:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='hushed.png" alt=":hushed:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='expressionless.png" alt=":expressionless:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='unamused.png" alt=":unamused:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='sweat_smile.png" alt=":sweat_smile:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='sweat.png" alt=":sweat:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='weary.png" alt=":weary:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='pensive.png" alt=":pensive:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='disappointed.png" alt=":disappointed:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='confounded.png" alt=":confounded:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='fearful.png" alt=":fearful:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='cold_sweat.png" alt=":cold_sweat:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='persevere.png" alt=":persevere:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='cry.png" alt=":cry:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='sob.png" alt=":sob:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='joy.png" alt=":joy:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='astonished.png" alt=":astonished:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='scream.png" alt=":scream:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='neckbeard.png" alt=":neckbeard:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='tired_face.png" alt=":tired_face:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='angry.png" alt=":angry:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='rage.png" alt=":rage:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='triumph.png" alt=":triumph:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='sleepy.png" alt=":sleepy:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='yum.png" alt=":yum:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='mask.png" alt=":mask:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='sunglasses.png" alt=":sunglasses:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='dizzy_face.png" alt=":dizzy_face:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='imp.png" alt=":imp:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='smiling_imp.png" alt=":smiling_imp:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='neutral_face.png" alt=":neutral_face:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='no_mouth.png" alt=":no_mouth:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='innocent.png" alt=":innocent:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='alien.png" alt=":alien:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='yellow_heart.png" alt=":yellow_heart:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='blue_heart.png" alt=":blue_heart:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='purple_heart.png" alt=":purple_heart:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='heart.png" alt=":heart:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='green_heart.png" alt=":green_heart:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='broken_heart.png" alt=":broken_heart:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='heartbeat.png" alt=":heartbeat:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='heartpulse.png" alt=":heartpulse:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='two_hearts.png" alt=":two_hearts:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='revolving_hearts.png" alt=":revolving_hearts:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='cupid.png" alt=":cupid:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='sparkling_heart.png" alt=":sparkling_heart:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='sparkles.png" alt=":sparkles:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='star.png" alt=":star:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='star2.png" alt=":star2:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='dizzy.png" alt=":dizzy:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='boom.png" alt=":boom:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='collision.png" alt=":collision:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='anger.png" alt=":anger:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='exclamation.png" alt=":exclamation:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='question.png" alt=":question:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='grey_exclamation.png" alt=":grey_exclamation:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='grey_question.png" alt=":grey_question:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='zzz.png" alt=":zzz:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='dash.png" alt=":dash:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='sweat_drops.png" alt=":sweat_drops:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='notes.png" alt=":notes:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='musical_note.png" alt=":musical_note:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='fire.png" alt=":fire:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='hankey.png" alt=":hankey:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='poop.png" alt=":poop:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='shit.png" alt=":shit:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='plus1.png" alt=":+1:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='thumbsup.png" alt=":thumbsup:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='-1.png" alt=":-1:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='thumbsdown.png" alt=":thumbsdown:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='ok_hand.png" alt=":ok_hand:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='punch.png" alt=":punch:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='facepunch.png" alt=":facepunch:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='fist.png" alt=":fist:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='v.png" alt=":v:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='wave.png" alt=":wave:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='hand.png" alt=":hand:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='open_hands.png" alt=":open_hands:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='point_up.png" alt=":point_up:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='point_down.png" alt=":point_down:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='point_left.png" alt=":point_left:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='point_right.png" alt=":point_right:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='raised_hands.png" alt=":raised_hands:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='pray.png" alt=":pray:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='point_up_2.png" alt=":point_up_2:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='clap.png" alt=":clap:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='muscle.png" alt=":muscle:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='walking.png" alt=":walking:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='runner.png" alt=":runner:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='running.png" alt=":running:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='couple.png" alt=":couple:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='family.png" alt=":family:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='two_men_holding_hands.png" alt=":two_men_holding_hands:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='two_women_holding_hands.png" alt=":two_women_holding_hands:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='dancer.png" alt=":dancer:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='dancers.png" alt=":dancers:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='ok_woman.png" alt=":ok_woman:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='no_good.png" alt=":no_good:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='information_desk_person.png" alt=":information_desk_person:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='raised_hand.png" alt=":raised_hand:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='bride_with_veil.png" alt=":bride_with_veil:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='person_with_pouting_face.png" alt=":person_with_pouting_face:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='person_frowning.png" alt=":person_frowning:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='bow.png" alt=":bow:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='couplekiss.png" alt=":couplekiss:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='couple_with_heart.png" alt=":couple_with_heart:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='massage.png" alt=":massage:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='haircut.png" alt=":haircut:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='nail_care.png" alt=":nail_care:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='boy.png" alt=":boy:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='girl.png" alt=":girl:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='woman.png" alt=":woman:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='man.png" alt=":man:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='baby.png" alt=":baby:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='older_woman.png" alt=":older_woman:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='older_man.png" alt=":older_man:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='person_with_blond_hair.png" alt=":person_with_blond_hair:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='man_with_gua_pi_mao.png" alt=":man_with_gua_pi_mao:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='man_with_turban.png" alt=":man_with_turban:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='construction_worker.png" alt=":construction_worker:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='cop.png" alt=":cop:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='angel.png" alt=":angel:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='princess.png" alt=":princess:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='smiley_cat.png" alt=":smiley_cat:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='smile_cat.png" alt=":smile_cat:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='heart_eyes_cat.png" alt=":heart_eyes_cat:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='kissing_cat.png" alt=":kissing_cat:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='smirk_cat.png" alt=":smirk_cat:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='scream_cat.png" alt=":scream_cat:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='crying_cat_face.png" alt=":crying_cat_face:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='joy_cat.png" alt=":joy_cat:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='pouting_cat.png" alt=":pouting_cat:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='japanese_ogre.png" alt=":japanese_ogre:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='japanese_goblin.png" alt=":japanese_goblin:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='see_no_evil.png" alt=":see_no_evil:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='hear_no_evil.png" alt=":hear_no_evil:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='speak_no_evil.png" alt=":speak_no_evil:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='guardsman.png" alt=":guardsman:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='skull.png" alt=":skull:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='feet.png" alt=":feet:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='lips.png" alt=":lips:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='kiss.png" alt=":kiss:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='droplet.png" alt=":droplet:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='ear.png" alt=":ear:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='eyes.png" alt=":eyes:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='nose.png" alt=":nose:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='tongue.png" alt=":tongue:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='love_letter.png" alt=":love_letter:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='bust_in_silhouette.png" alt=":bust_in_silhouette:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='busts_in_silhouette.png" alt=":busts_in_silhouette:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='speech_balloon.png" alt=":speech_balloon:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='thought_balloon.png" alt=":thought_balloon:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='feelsgood.png" alt=":feelsgood:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='finnadie.png" alt=":finnadie:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='goberserk.png" alt=":goberserk:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='godmode.png" alt=":godmode:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='hurtrealbad.png" alt=":hurtrealbad:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='rage1.png" alt=":rage1:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='rage2.png" alt=":rage2:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='rage3.png" alt=":rage3:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='rage4.png" alt=":rage4:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='suspect.png" alt=":suspect:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='trollface.png" alt=":trollface:" id="emoca" class="wp-smiley">';
	
	
	return $emo;
	
	
}

function Nature(){

	$default2 = includes_url( 'images/smilies/emojis/' );
	
	$emo='<img src="'; $emo.=$default2; $emo.='sunny.png" alt=":sunny:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='umbrella.png" alt=":umbrella:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='cloud.png" alt=":cloud:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='snowflake.png" alt=":snowflake:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='snowman.png" alt=":snowman:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='zap.png" alt=":zap:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='cyclone.png" alt=":cyclone:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='foggy.png" alt=":foggy:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='ocean.png" alt=":ocean:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='cat.png" alt=":cat:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='dog.png" alt=":dog:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='mouse.png" alt=":mouse:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='hamster.png" alt=":hamster:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='rabbit.png" alt=":rabbit:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='wolf.png" alt=":wolf:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='frog.png" alt=":frog:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='tiger.png" alt=":tiger:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='koala.png" alt=":koala:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='bear.png" alt=":bear:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='pig.png" alt=":pig:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='pig_nose.png" alt=":pig_nose:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='cow.png" alt=":cow:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='boar.png" alt=":boar:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='monkey_face.png" alt=":monkey_face:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='monkey.png" alt=":monkey:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='horse.png" alt=":horse:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='racehorse.png" alt=":racehorse:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='camel.png" alt=":camel:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='sheep.png" alt=":sheep:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='elephant.png" alt=":elephant:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='panda_face.png" alt=":panda_face:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='snake.png" alt=":snake:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='bird.png" alt=":bird:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='baby_chick.png" alt=":baby_chick:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='hatched_chick.png" alt=":hatched_chick:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='hatching_chick.png" alt=":hatching_chick:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='chicken.png" alt=":chicken:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='penguin.png" alt=":penguin:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='turtle.png" alt=":turtle:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='bug.png" alt=":bug:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='honeybee.png" alt=":honeybee:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='ant.png" alt=":ant:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='beetle.png" alt=":beetle:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='snail.png" alt=":snail:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='octopus.png" alt=":octopus:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='tropical_fish.png" alt=":tropical_fish:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='fish.png" alt=":fish:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='whale.png" alt=":whale:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='whale2.png" alt=":whale2:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='dolphin.png" alt=":dolphin:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='cow2.png" alt=":cow2:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='ram.png" alt=":ram:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='rat.png" alt=":rat:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='water_buffalo.png" alt=":water_buffalo:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='tiger2.png" alt=":tiger2:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='rabbit2.png" alt=":rabbit2:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='dragon.png" alt=":dragon:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='goat.png" alt=":goat:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='rooster.png" alt=":rooster:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='dog2.png" alt=":dog2:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='pig2.png" alt=":pig2:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='mouse2.png" alt=":mouse2:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='ox.png" alt=":ox:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='dragon_face.png" alt=":dragon_face:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='blowfish.png" alt=":blowfish:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='crocodile.png" alt=":crocodile:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='dromedary_camel.png" alt=":dromedary_camel:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='leopard.png" alt=":leopard:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='cat2.png" alt=":cat2:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='poodle.png" alt=":poodle:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='paw_prints.png" alt=":paw_prints:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='bouquet.png" alt=":bouquet:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='cherry_blossom.png" alt=":cherry_blossom:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='tulip.png" alt=":tulip:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='four_leaf_clover.png" alt=":four_leaf_clover:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='rose.png" alt=":rose:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='sunflower.png" alt=":sunflower:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='hibiscus.png" alt=":hibiscus:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='maple_leaf.png" alt=":maple_leaf:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='leaves.png" alt=":leaves:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='fallen_leaf.png" alt=":fallen_leaf:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='herb.png" alt=":herb:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='mushroom.png" alt=":mushroom:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='cactus.png" alt=":cactus:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='palm_tree.png" alt=":palm_tree:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='evergreen_tree.png" alt=":evergreen_tree:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='deciduous_tree.png" alt=":deciduous_tree:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='chestnut.png" alt=":chestnut:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='seedling.png" alt=":seedling:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='blossom.png" alt=":blossom:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='ear_of_rice.png" alt=":ear_of_rice:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='shell.png" alt=":shell:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='globe_with_meridians.png" alt=":globe_with_meridians:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='sun_with_face.png" alt=":sun_with_face:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='full_moon_with_face.png" alt=":full_moon_with_face:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='new_moon_with_face.png" alt=":new_moon_with_face:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='new_moon.png" alt=":new_moon:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='waxing_crescent_moon.png" alt=":waxing_crescent_moon:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='first_quarter_moon.png" alt=":first_quarter_moon:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='waxing_gibbous_moon.png" alt=":waxing_gibbous_moon:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='full_moon.png" alt=":full_moon:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='waning_gibbous_moon.png" alt=":waning_gibbous_moon:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='last_quarter_moon.png" alt=":last_quarter_moon:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='waning_crescent_moon.png" alt=":waning_crescent_moon:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='last_quarter_moon_with_face.png" alt=":last_quarter_moon_with_face:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='first_quarter_moon_with_face.png" alt=":first_quarter_moon_with_face:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='moon.png" alt=":moon:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='earth_africa.png" alt=":earth_africa:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='earth_americas.png" alt=":earth_americas:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='earth_asia.png" alt=":earth_asia:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='volcano.png" alt=":volcano:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='milky_way.png" alt=":milky_way:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='partly_sunny.png" alt=":partly_sunny:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='octocat.png" alt=":octocat:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='squirrel.png" alt=":squirrel:" id="emoca" class="wp-smiley">';	

return $emo;
}





function objects(){
	
	$default2 = includes_url( 'images/smilies/emojis/' );

	$emo='<img src="'; $emo.=$default2; $emo.='bamboo.png" alt=":bamboo:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='gift_heart.png" alt=":gift_heart:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='dolls.png" alt=":dolls:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='school_satchel.png" alt=":school_satchel:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='mortar_board.png" alt=":mortar_board:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='flags.png" alt=":flags:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='fireworks.png" alt=":fireworks:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='sparkler.png" alt=":sparkler:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='wind_chime.png" alt=":wind_chime:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='rice_scene.png" alt=":rice_scene:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='jack_o_lantern.png" alt=":jack_o_lantern:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='ghost.png" alt=":ghost:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='santa.png" alt=":santa:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='christmas_tree.png" alt=":christmas_tree:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='gift.png" alt=":gift:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='bell.png" alt=":bell:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='no_bell.png" alt=":no_bell:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='tanabata_tree.png" alt=":tanabata_tree:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='tada.png" alt=":tada:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='confetti_ball.png" alt=":confetti_ball:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='balloon.png" alt=":balloon:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='crystal_ball.png" alt=":crystal_ball:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='cd.png" alt=":cd:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='dvd.png" alt=":dvd:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='floppy_disk.png" alt=":floppy_disk:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='camera.png" alt=":camera:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='video_camera.png" alt=":video_camera:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='movie_camera.png" alt=":movie_camera:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='computer.png" alt=":computer:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='tv.png" alt=":tv:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='iphone.png" alt=":iphone:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='phone.png" alt=":phone:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='telephone.png" alt=":telephone:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='telephone_receiver.png" alt=":telephone_receiver:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='pager.png" alt=":pager:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='fax.png" alt=":fax:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='minidisc.png" alt=":minidisc:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='vhs.png" alt=":vhs:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='sound.png" alt=":sound:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='speaker.png" alt=":speaker:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='mute.png" alt=":mute:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='loudspeaker.png" alt=":loudspeaker:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='mega.png" alt=":mega:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='hourglass.png" alt=":hourglass:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='hourglass_flowing_sand.png" alt=":hourglass_flowing_sand:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='alarm_clock.png" alt=":alarm_clock:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='watch.png" alt=":watch:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='radio.png" alt=":radio:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='satellite.png" alt=":satellite:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='loop.png" alt=":loop:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='mag.png" alt=":mag:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='mag_right.png" alt=":mag_right:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='unlock.png" alt=":unlock:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='lock.png" alt=":lock:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='lock_with_ink_pen.png" alt=":lock_with_ink_pen:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='closed_lock_with_key.png" alt=":closed_lock_with_key:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='key.png" alt=":key:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='bulb.png" alt=":bulb:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='flashlight.png" alt=":flashlight:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='high_brightness.png" alt=":high_brightness:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='low_brightness.png" alt=":low_brightness:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='electric_plug.png" alt=":electric_plug:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='battery.png" alt=":battery:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='calling.png" alt=":calling:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='email.png" alt=":email:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='mailbox.png" alt=":mailbox:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='postbox.png" alt=":postbox:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='bath.png" alt=":bath:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='bathtub.png" alt=":bathtub:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='shower.png" alt=":shower:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='toilet.png" alt=":toilet:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='wrench.png" alt=":wrench:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='nut_and_bolt.png" alt=":nut_and_bolt:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='hammer.png" alt=":hammer:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='seat.png" alt=":seat:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='moneybag.png" alt=":moneybag:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='yen.png" alt=":yen:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='dollar.png" alt=":dollar:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='pound.png" alt=":pound:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='euro.png" alt=":euro:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='credit_card.png" alt=":credit_card:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='money_with_wings.png" alt=":money_with_wings:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='e-mail.png" alt=":e-mail:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='inbox_tray.png" alt=":inbox_tray:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='outbox_tray.png" alt=":outbox_tray:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='envelope.png" alt=":envelope:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='incoming_envelope.png" alt=":incoming_envelope:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='postal_horn.png" alt=":postal_horn:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='mailbox_closed.png" alt=":mailbox_closed:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='mailbox_with_mail.png" alt=":mailbox_with_mail:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='mailbox_with_no_mail.png" alt=":mailbox_with_no_mail:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='door.png" alt=":door:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='smoking.png" alt=":smoking:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='bomb.png" alt=":bomb:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='gun.png" alt=":gun:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='hocho.png" alt=":hocho:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='pill.png" alt=":pill:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='syringe.png" alt=":syringe:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='page_facing_up.png" alt=":page_facing_up:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='page_with_curl.png" alt=":page_with_curl:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='bookmark_tabs.png" alt=":bookmark_tabs:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='bar_chart.png" alt=":bar_chart:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='chart_with_upwards_trend.png" alt=":chart_with_upwards_trend:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='chart_with_downwards_trend.png" alt=":chart_with_downwards_trend:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='scroll.png" alt=":scroll:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='clipboard.png" alt=":clipboard:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='calendar.png" alt=":calendar:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='date.png" alt=":date:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='card_index.png" alt=":card_index:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='file_folder.png" alt=":file_folder:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='open_file_folder.png" alt=":open_file_folder:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='scissors.png" alt=":scissors:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='pushpin.png" alt=":pushpin:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='paperclip.png" alt=":paperclip:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='black_nib.png" alt=":black_nib:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='pencil2.png" alt=":pencil2:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='straight_ruler.png" alt=":straight_ruler:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='triangular_ruler.png" alt=":triangular_ruler:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='closed_book.png" alt=":closed_book:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='green_book.png" alt=":green_book:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='blue_book.png" alt=":blue_book:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='orange_book.png" alt=":orange_book:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='notebook.png" alt=":notebook:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='notebook_with_decorative_cover.png" alt=":notebook_with_decorative_cover:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='ledger.png" alt=":ledger:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='books.png" alt=":books:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='bookmark.png" alt=":bookmark:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='name_badge.png" alt=":name_badge:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='microscope.png" alt=":microscope:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='telescope.png" alt=":telescope:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='newspaper.png" alt=":newspaper:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='football.png" alt=":football:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='basketball.png" alt=":basketball:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='soccer.png" alt=":soccer:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='baseball.png" alt=":baseball:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='tennis.png" alt=":tennis:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='8ball.png" alt=":8ball:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='rugby_football.png" alt=":rugby_football:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='bowling.png" alt=":bowling:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='golf.png" alt=":golf:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='mountain_bicyclist.png" alt=":mountain_bicyclist:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='bicyclist.png" alt=":bicyclist:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='horse_racing.png" alt=":horse_racing:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='snowboarder.png" alt=":snowboarder:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='swimmer.png" alt=":swimmer:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='surfer.png" alt=":surfer:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='ski.png" alt=":ski:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='spades.png" alt=":spades:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='hearts.png" alt=":hearts:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='clubs.png" alt=":clubs:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='diamonds.png" alt=":diamonds:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='gem.png" alt=":gem:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='ring.png" alt=":ring:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='trophy.png" alt=":trophy:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='musical_score.png" alt=":musical_score:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='musical_keyboard.png" alt=":musical_keyboard:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='violin.png" alt=":violin:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='space_invader.png" alt=":space_invader:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='video_game.png" alt=":video_game:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='black_joker.png" alt=":black_joker:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='flower_playing_cards.png" alt=":flower_playing_cards:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='game_die.png" alt=":game_die:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='dart.png" alt=":dart:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='mahjong.png" alt=":mahjong:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='clapper.png" alt=":clapper:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='memo.png" alt=":memo:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='pencil.png" alt=":pencil:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='book.png" alt=":book:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='art.png" alt=":art:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='microphone.png" alt=":microphone:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='headphones.png" alt=":headphones:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='trumpet.png" alt=":trumpet:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='saxophone.png" alt=":saxophone:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='guitar.png" alt=":guitar:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='shoe.png" alt=":shoe:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='sandal.png" alt=":sandal:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='high_heel.png" alt=":high_heel:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='lipstick.png" alt=":lipstick:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='boot.png" alt=":boot:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='shirt.png" alt=":shirt:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='tshirt.png" alt=":tshirt:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='necktie.png" alt=":necktie:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='womans_clothes.png" alt=":womans_clothes:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='dress.png" alt=":dress:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='running_shirt_with_sash.png" alt=":running_shirt_with_sash:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='jeans.png" alt=":jeans:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='kimono.png" alt=":kimono:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='bikini.png" alt=":bikini:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='ribbon.png" alt=":ribbon:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='tophat.png" alt=":tophat:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='crown.png" alt=":crown:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='womans_hat.png" alt=":womans_hat:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='mans_shoe.png" alt=":mans_shoe:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='closed_umbrella.png" alt=":closed_umbrella:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='briefcase.png" alt=":briefcase:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='handbag.png" alt=":handbag:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='pouch.png" alt=":pouch:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='purse.png" alt=":purse:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='eyeglasses.png" alt=":eyeglasses:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='fishing_pole_and_fish.png" alt=":fishing_pole_and_fish:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='coffee.png" alt=":coffee:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='tea.png" alt=":tea:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='sake.png" alt=":sake:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='baby_bottle.png" alt=":baby_bottle:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='beer.png" alt=":beer:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='beers.png" alt=":beers:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='cocktail.png" alt=":cocktail:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='tropical_drink.png" alt=":tropical_drink:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='wine_glass.png" alt=":wine_glass:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='fork_and_knife.png" alt=":fork_and_knife:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='pizza.png" alt=":pizza:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='hamburger.png" alt=":hamburger:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='fries.png" alt=":fries:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='poultry_leg.png" alt=":poultry_leg:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='meat_on_bone.png" alt=":meat_on_bone:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='spaghetti.png" alt=":spaghetti:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='curry.png" alt=":curry:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='fried_shrimp.png" alt=":fried_shrimp:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='bento.png" alt=":bento:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='sushi.png" alt=":sushi:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='fish_cake.png" alt=":fish_cake:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='rice_ball.png" alt=":rice_ball:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='rice_cracker.png" alt=":rice_cracker:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='rice.png" alt=":rice:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='ramen.png" alt=":ramen:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='stew.png" alt=":stew:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='oden.png" alt=":oden:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='dango.png" alt=":dango:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='egg.png" alt=":egg:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='bread.png" alt=":bread:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='doughnut.png" alt=":doughnut:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='custard.png" alt=":custard:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='icecream.png" alt=":icecream:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='ice_cream.png" alt=":ice_cream:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='shaved_ice.png" alt=":shaved_ice:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='birthday.png" alt=":birthday:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='cake.png" alt=":cake:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='cookie.png" alt=":cookie:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='chocolate_bar.png" alt=":chocolate_bar:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='candy.png" alt=":candy:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='lollipop.png" alt=":lollipop:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='honey_pot.png" alt=":honey_pot:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='apple.png" alt=":apple:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='green_apple.png" alt=":green_apple:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='tangerine.png" alt=":tangerine:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='lemon.png" alt=":lemon:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='cherries.png" alt=":cherries:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='grapes.png" alt=":grapes:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='watermelon.png" alt=":watermelon:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='strawberry.png" alt=":strawberry:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='peach.png" alt=":peach:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='melon.png" alt=":melon:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='banana.png" alt=":banana:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='pear.png" alt=":pear:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='pineapple.png" alt=":pineapple:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='sweet_potato.png" alt=":sweet_potato:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='eggplant.png" alt=":eggplant:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='tomato.png" alt=":tomato:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='corn.png" alt=":corn:" id="emoca" class="wp-smiley">';
	
	return $emo;

}

function places(){
	
	$default2 = includes_url( 'images/smilies/emojis/' );
	
	$emo='<img src="'; $emo.=$default2; $emo.='onezeronine.png" alt=":109:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='house.png" alt=":house:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='house_with_garden.png" alt=":house_with_garden:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='school.png" alt=":school:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='office.png" alt=":office:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='post_office.png" alt=":post_office:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='hospital.png" alt=":hospital:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='bank.png" alt=":bank:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='convenience_store.png" alt=":convenience_store:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='love_hotel.png" alt=":love_hotel:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='hotel.png" alt=":hotel:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='wedding.png" alt=":wedding:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='church.png" alt=":church:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='department_store.png" alt=":department_store:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='european_post_office.png" alt=":european_post_office:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='city_sunrise.png" alt=":city_sunrise:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='city_sunset.png" alt=":city_sunset:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='japanese_castle.png" alt=":japanese_castle:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='european_castle.png" alt=":european_castle:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='tent.png" alt=":tent:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='factory.png" alt=":factory:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='tokyo_tower.png" alt=":tokyo_tower:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='japan.png" alt=":japan:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='mount_fuji.png" alt=":mount_fuji:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='sunrise_over_mountains.png" alt=":sunrise_over_mountains:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='sunrise.png" alt=":sunrise:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='stars.png" alt=":stars:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='statue_of_liberty.png" alt=":statue_of_liberty:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='bridge_at_night.png" alt=":bridge_at_night:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='carousel_horse.png" alt=":carousel_horse:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='rainbow.png" alt=":rainbow:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='ferris_wheel.png" alt=":ferris_wheel:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='fountain.png" alt=":fountain:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='roller_coaster.png" alt=":roller_coaster:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='ship.png" alt=":ship:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='speedboat.png" alt=":speedboat:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='boat.png" alt=":boat:" id="emoca" class="wp-smiley">&nbsp;
	<img src="'; $emo.=$default2; $emo.='rowboat.png" alt=":rowboat:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='anchor.png" alt=":anchor:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='rocket.png" alt=":rocket:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='airplane.png" alt=":airplane:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='helicopter.png" alt=":helicopter:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='steam_locomotive.png" alt=":steam_locomotive:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='tram.png" alt=":tram:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='mountain_railway.png" alt=":mountain_railway:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='bike.png" alt=":bike:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='aerial_tramway.png" alt=":aerial_tramway:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='suspension_railway.png" alt=":suspension_railway:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='mountain_cableway.png" alt=":mountain_cableway:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='tractor.png" alt=":tractor:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='blue_car.png" alt=":blue_car:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='oncoming_automobile.png" alt=":oncoming_automobile:" id="emoca" class="wp-smiley">&nbsp;
	<img src="'; $emo.=$default2; $emo.='red_car.png" alt=":red_car:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='taxi.png" alt=":taxi:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='oncoming_taxi.png" alt=":oncoming_taxi:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='articulated_lorry.png" alt=":articulated_lorry:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='bus.png" alt=":bus:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='oncoming_bus.png" alt=":oncoming_bus:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='rotating_light.png" alt=":rotating_light:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='police_car.png" alt=":police_car:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='oncoming_police_car.png" alt=":oncoming_police_car:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='fire_engine.png" alt=":fire_engine:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='ambulance.png" alt=":ambulance:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='minibus.png" alt=":minibus:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='truck.png" alt=":truck:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='train.png" alt=":train:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='station.png" alt=":station:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='train2.png" alt=":train2:" id="emoca" class="wp-smiley">&nbsp;
	<img src="'; $emo.=$default2; $emo.='bullettrain_side.png" alt=":bullettrain_side:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='light_rail.png" alt=":light_rail:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='monorail.png" alt=":monorail:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='railway_car.png" alt=":railway_car:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='trolleybus.png" alt=":trolleybus:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='ticket.png" alt=":ticket:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='fuelpump.png" alt=":fuelpump:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='vertical_traffic_light.png" alt=":vertical_traffic_light:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='traffic_light.png" alt=":traffic_light:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='warning.png" alt=":warning:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='construction.png" alt=":construction:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='beginner.png" alt=":beginner:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='atm.png" alt=":atm:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='slot_machine.png" alt=":slot_machine:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='busstop.png" alt=":busstop:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='barber.png" alt=":barber:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='hotsprings.png" alt=":hotsprings:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='checkered_flag.png" alt=":checkered_flag:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='crossed_flags.png" alt=":crossed_flags:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='izakaya_lantern.png" alt=":izakaya_lantern:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='performing_arts.png" alt=":moyai:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='circus_tent.png" alt=":circus_tent:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='performing_arts.png" alt=":performing_arts:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='round_pushpin.png" alt=":round_pushpin:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='triangular_flag_on_post.png" alt=":triangular_flag_on_post:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='jp.png" alt=":jp:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='kr.png" alt=":kr:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='cn.png" alt=":cn:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='us.png" alt=":us:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='fr.png" alt=":fr:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='es.png" alt=":es:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='it.png" alt=":it:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='ru.png" alt=":ru:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='gb.png" alt=":gb:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='uk.png" alt=":uk:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='de.png" alt=":de:" id="emoca" class="wp-smiley">';
	
	return $emo;

}

function symbols(){
	
	$default2 = includes_url( 'images/smilies/emojis/' );

	$emo='<img src="'; $emo.=$default2; $emo.='one.png" alt=":one:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='two.png" alt=":two:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='three.png" alt=":three:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='four.png" alt=":four:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='five.png" alt=":five:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='six.png" alt=":six:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='seven.png" alt=":seven:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='eight.png" alt=":eight:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='nine.png" alt=":nine:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='keycap_ten.png" alt=":keycap_ten:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='1234.png" alt=":1234:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='zero.png" alt=":zero:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='hash.png" alt=":hash:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='symbols.png" alt=":symbols:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='arrow_backward.png" alt=":arrow_backward:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='arrow_down.png" alt=":arrow_down:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='arrow_forward.png" alt=":arrow_forward:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='arrow_left.png" alt=":arrow_left:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='capital_abcd.png" alt=":capital_abcd:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='abcd.png" alt=":abcd:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='abc.png" alt=":abc:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='arrow_lower_left.png" alt=":arrow_lower_left:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='arrow_lower_right.png" alt=":arrow_lower_right:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='arrow_right.png" alt=":arrow_right:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='arrow_up.png" alt=":arrow_up:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='arrow_upper_left.png" alt=":arrow_upper_left:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='arrow_upper_right.png" alt=":arrow_upper_right:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='arrow_double_down.png" alt=":arrow_double_down:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='arrow_double_up.png" alt=":arrow_double_up:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='arrow_down_small.png" alt=":arrow_down_small:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='arrow_heading_down.png" alt=":arrow_heading_down:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='arrow_heading_up.png" alt=":arrow_heading_up:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='leftwards_arrow_with_hook.png" alt=":leftwards_arrow_with_hook:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='arrow_right_hook.png" alt=":arrow_right_hook:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='left_right_arrow.png" alt=":left_right_arrow:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='arrow_up_down.png" alt=":arrow_up_down:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='arrow_up_small.png" alt=":arrow_up_small:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='arrows_clockwise.png" alt=":arrows_clockwise:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='arrows_counterclockwise.png" alt=":arrows_counterclockwise:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='rewind.png" alt=":rewind:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='fast_forward.png" alt=":fast_forward:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='information_source.png" alt=":information_source:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='ok.gif" alt=":ok:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='twisted_rightwards_arrows.png" alt=":twisted_rightwards_arrows:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='repeat.png" alt=":repeat:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='repeat_one.png" alt=":repeat_one:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='new.png" alt=":new:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='top.png" alt=":top:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='up.png" alt=":up:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='cool.png" alt=":cool:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='free.png" alt=":free:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='ng.png" alt=":ng:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='cinema.png" alt=":cinema:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='koko.png" alt=":koko:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='signal_strength.png" alt=":signal_strength:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='u5272.png" alt=":u5272:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='u5408.png" alt=":u5408:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='u55b6.png" alt=":u55b6:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='u6307.png" alt=":u6307:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='u6708.png" alt=":u6708:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='u6709.png" alt=":u6709:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='u6e80.png" alt=":u6e80:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='u7121.png" alt=":u7121:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='u7533.png" alt=":u7533:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='u7a7a.png" alt=":u7a7a:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='u7981.png" alt=":u7981:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='sa.png" alt=":sa:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='restroom.png" alt=":restroom:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='mens.png" alt=":mens:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='womens.png" alt=":womens:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='baby_symbol.png" alt=":baby_symbol:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='no_smoking.png" alt=":no_smoking:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='parking.png" alt=":parking:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='wheelchair.png" alt=":wheelchair:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='metro.png" alt=":metro:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='baggage_claim.png" alt=":baggage_claim:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='accept.png" alt=":accept:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='wc.png" alt=":wc:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='potable_water.png" alt=":potable_water:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='put_litter_in_its_place.png" alt=":put_litter_in_its_place:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='secret.png" alt=":secret:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='congratulations.png" alt=":congratulations:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='m.png" alt=":m:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='passport_control.png" alt=":passport_control:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='left_luggage.png" alt=":left_luggage:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='customs.png" alt=":customs:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='ideograph_advantage.png" alt=":ideograph_advantage:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='cl.png" alt=":cl:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='sos.png" alt=":sos:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='id.png" alt=":id:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='no_entry_sign.png" alt=":no_entry_sign:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='underage.png" alt=":underage:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='no_mobile_phones.png" alt=":no_mobile_phones:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='do_not_litter.png" alt=":do_not_litter:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='non-potable_water.png" alt=":non-potable_water:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='no_bicycles.png" alt=":no_bicycles:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='no_pedestrians.png" alt=":no_pedestrians:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='children_crossing.png" alt=":children_crossing:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='no_entry.png" alt=":no_entry:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='eight_spoked_asterisk.png" alt=":eight_spoked_asterisk:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='eight_pointed_black_star.png" alt=":eight_pointed_black_star:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='heart_decoration.png" alt=":heart_decoration:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='vs.png" alt=":vs:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='vibration_mode.png" alt=":vibration_mode:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='mobile_phone_off.png" alt=":mobile_phone_off:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='chart.png" alt=":chart:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='currency_exchange.png" alt=":currency_exchange:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='aries.png" alt=":aries:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='taurus.png" alt=":taurus:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='gemini.png" alt=":gemini:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='cancer.png" alt=":cancer:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='leo.png" alt=":leo:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='virgo.png" alt=":virgo:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='libra.png" alt=":libra:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='scorpius.png" alt=":scorpius:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='sagittarius.png" alt=":sagittarius:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='capricorn.png" alt=":capricorn:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='aquarius.png" alt=":aquarius:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='pisces.png" alt=":pisces:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='ophiuchus.png" alt=":ophiuchus:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='six_pointed_star.png" alt=":six_pointed_star:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='negative_squared_cross_mark.png" alt=":negative_squared_cross_mark:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='a.png" alt=":a:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='b.png" alt=":b:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='ab.png" alt=":ab:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='o2.png" alt=":o2:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='diamond_shape_with_a_dot_inside.png" alt=":diamond_shape_with_a_dot_inside:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='recycle.png" alt=":recycle:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='end.png" alt=":end:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='on.png" alt=":on:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='soon.png" alt=":soon:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='clock1.png" alt=":clock1:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='clock130.png" alt=":clock130:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='clock10.png" alt=":clock10:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='clock1030.png" alt=":clock1030:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='clock11.png" alt=":clock11:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='clock1130.png" alt=":clock1130:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='clock12.png" alt=":clock12:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='clock1230.png" alt=":clock1230:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='clock2.png" alt=":clock2:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='clock230.png" alt=":clock230:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='clock3.png" alt=":clock3:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='clock330.png" alt=":clock330:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='clock4.png" alt=":clock4:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='clock430.png" alt=":clock430:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='clock5.png" alt=":clock5:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='clock530.png" alt=":clock530:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='clock6.png" alt=":clock6:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='clock630.png" alt=":clock630:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='clock7.png" alt=":clock7:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='clock730.png" alt=":clock730:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='clock8.png" alt=":clock8:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='clock830.png" alt=":clock830:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='clock9.png" alt=":clock9:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='clock930.png" alt=":clock930:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='heavy_dollar_sign.png" alt=":heavy_dollar_sign:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='copyright.png" alt=":copyright:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='registered.png" alt=":registered:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='tm.png" alt=":tm:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='x.png" alt=":x:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='heavy_exclamation_mark.png" alt=":heavy_exclamation_mark:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='bangbang.png" alt=":bangbang:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='interrobang.png" alt=":interrobang:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='o.png" alt=":o:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='heavy_multiplication_x.png" alt=":heavy_multiplication_x:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='heavy_plus_sign.png" alt=":heavy_plus_sign:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='heavy_minus_sign.png" alt=":heavy_minus_sign:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='heavy_division_sign.png" alt=":heavy_division_sign:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='white_flower.png" alt=":white_flower:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='100.png" alt=":100:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='heavy_check_mark.png" alt=":heavy_check_mark:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='ballot_box_with_check.png" alt=":ballot_box_with_check:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='radio_button.png" alt=":radio_button:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='link.png" alt=":link:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='curly_loop.png" alt=":curly_loop:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='wavy_dash.png" alt=":wavy_dash:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='part_alternation_mark.png" alt=":part_alternation_mark:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='trident.png" alt=":trident:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='black_square.png" alt=":black_square:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='white_square.png" alt=":white_square:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='white_check_mark.png" alt=":white_check_mark:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='black_square_button.png" alt=":black_square_button:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='white_square_button.png" alt=":white_square_button:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='black_circle.png" alt=":black_circle:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='white_circle.png" alt=":white_circle:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='red_circle.png" alt=":red_circle:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='large_blue_circle.png" alt=":large_blue_circle:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='large_blue_diamond.png" alt=":large_blue_diamond:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='large_orange_diamond.png" alt=":large_orange_diamond:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='small_blue_diamond.png" alt=":small_blue_diamond:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='small_orange_diamond.png" alt=":small_orange_diamond:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='small_red_triangle.png" alt=":small_red_triangle:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='small_red_triangle_down.png" alt=":small_red_triangle_down:" id="emoca" class="wp-smiley">
	<img src="'; $emo.=$default2; $emo.='shipit.png" alt=":shipit:" id="emoca" class="wp-smiley">';
	
	return $emo;

}

?>